
db.City.insert({_id:BinData(3,"CdMXwr728ee1rTdfncdJ3Q=="),formatted_address:"Cologne, Germany"})
db.City.insert({_id:BinData(3,"CDMXwr728Ee1rTdfncdJ3Q=="),formatted_address:"Berlin, Germany"})
db.City.insert({_id:BinData(3,"CDMXwr728Ee1rT2ddcdJ3Q=="),formatted_address:"Hamburg, Germany"})
db.City.insert({_id:BinData(3,"CDMXwr728Ee1rT2dwicJ3Q=="),formatted_address:"Munich, Germany"})
db.City.insert({_id:BinData(3,"CDMXwrxmdEe1rT2dwicJ3Q=="),formatted_address:"Frankfurt, Germany"})
db.City.insert({_id:BinData(3,"CDMXw3hddEe1rT2dwicJ3Q=="),formatted_address:"Stuttgart, Germany"})
db.City.insert({_id:BinData(3,"CDMXwrxmdEed8a2dwicJ3Q=="),formatted_address:"Düsseldorf, Germany"})
db.City.insert({_id:BinData(3,"CDMXwrxmdEe39dkewicJ3Q=="),formatted_address:"Dortmund, Germany"})
db.City.insert({_id:BinData(3,"CDMXcxn39djkfT2dwicJ3Q=="),formatted_address:"Essen, Germany"})
db.City.insert({_id:BinData(3,"CDMXcxasd4gadT2dwicJ3Q=="),formatted_address:"Bremen, Germany"})
db.City.insert({_id:BinData(3,"CDMXcxn39djkfT2dasdf4a=="),formatted_address:"Leipzig, Germany"})
db.City.insert({_id:BinData(3,"CDMXcxn39djkfT2dwicJ3Q=="),formatted_address:"Dresden, Germany"})
db.City.insert({_id:BinData(3,"CDMXcxn39djkfdfascJ3dd=="),formatted_address:"Hannover, Germany"})
db.City.insert({_id:BinData(3,"dadcasn39djkfT2dwicJa3=="),formatted_address:"Nuremberg, Germany"})
db.City.insert({_id:BinData(3,"Sh58fnn39djkfT2dwicJ3Q=="),formatted_address:"Duisburg, Germany"})

db.Event.find({lastUpdatedTimestamp: {$gt: new Date(new Date().getTime() - 600000)}})